[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi==0.110.2",
    "passlib[bcrypt]==1.7.4",
    "sqlalchemy==2.0.29",
    "uvicorn==0.29.0",
]
